# Jupyter Book settings

title: "A short intro to web frontend"
author: Thierry Parmentelat
logo: ../media/logo.png

repository:
  url: https://github.com/ue22/web-intro
  branch: main
  path_to_book: notebooks

html:
  use_repository_button: yes
  use_edit_page_button: yes
  use_issues_button: yes

###

only_build_toc_files: true

execute:
#  execute_notebooks: "force"
  execute_notebooks: cache

sphinx:
  config:
    nb_custom_formats:
      .py:
        - jupytext.reads
        - fmt: py:percent

# for raw <img> tags in markdown
parse:
  myst_enable_extensions:
    - html_image
