all: resume.min.js spinning-wheel.min.js fibonacci.min.js pythagore.min.js

resume-blink.min.js: resume-blink.js
	node-minify -c butternut -i resume-blink.js -o resume-blink.min.js
spinning-wheel.min.js: spinning-wheel.js
	node-minify -c butternut -i spinning-wheel.js -o spinning-wheel.min.js
fibonacci.min.js: fibonacci.js
	node-minify -c butternut -i fibonacci.js -o fibonacci.min.js
pythagore.min.js: pythagore.js
	node-minify -c butternut -i pythagore.js -o pythagore.min.js
